### ISSUE TITLE
Browser console warning when initializing the chat

### ISSUE THREAD

**Issue by idosius** [rfoel/use-zendesk#125]
When intializing the chat, there is a browser console warning about the `setLocale` method ([please see latest API](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/web/sdk_api_reference/#set-locale)):

```
Error: 
Method webWidget.setLocale does not exist.

A note from Zendesk: API methods associated with the Web Widget (Classic) are still being executed on this page. This website is now using the new Web SDK (messaging experience) which no longer supports these APIs. If you don't intend to use the Web Widget (Classic), we recommend that you remove this code from your website.  Whilst not recommended, leaving them won't cause any issues. 

    at Ke (web-widget-9081-ea2ed2b.js:1:103973)
    at web-widget-9081-ea2ed2b.js:1:104748
    at Array.forEach (<anonymous>)
    at Object.run (web-widget-9081-ea2ed2b.js:1:104721)
    at web-widget-9081-ea2ed2b.js:1:307598
    at Array.forEach (<anonymous>)
    at web-widget-9081-ea2ed2b.js:1:307526
    at l (web-widget-6281-ea2ed2b.js:2:855911)
    at Generator._invoke (web-widget-6281-ea2ed2b.js:2:855699)
    at Generator.next (web-widget-6281-ea2ed2b.js:2:856336)
```

**Comment by thawinwats** [comment]
I noticed that the method has been changed

```
// from
zE('webWidget', 'setLocale', locale)

// to
zE('messenger:set', 'locale', newLocale<string>)
```

For more details, you can refer to the Zendesk API documentation.
https://developer.zendesk.com/api-reference/widget-messaging/web/core/#set-locale
